#FROM stephenliu/mono_from_source
FROM dbbd17125fe1

# install latest k runtime
RUN bin/bash -c "curl https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.kre/kvm/kvm.sh"
